### ISSUE TITLE
monetization.js file blocked by Ublock

### ISSUE THREAD

**Issue by thomasbnt** [devcer/eleventy-plugin-monetization#1]
**Describe the bug**
Great module, but your `monetization.js` is blocked when we uses Ublock or other content. Rename this file to `webmone.js` for example ✌

**To Reproduce**
1. Go to https://danielcanetti.com/demo/monetize-plugin/
2. F12 or CTRL+MAJ+I for open Inspect 
4. See Console
5. Error.

**Expected behavior**
No errors to get this file with Ublock or other tools who block this content name.

**Screenshots**
![image](https://user-images.githubusercontent.com/14293805/82688008-698b1880-9c58-11ea-8a87-1b609f279a5b.png)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser: Chrome with **Ublock Origins**
 - Version: 80

**Comment by DanCanetti** [comment]
This should now be resolved. File renamed to monet.js.

Please install the latest package from NPM and let me know if you have any further issues.

**Comment by thomasbnt** [comment]
Could you update [your page](https://danielcanetti.com/demo/monetize-plugin/) ?

:new: You can [see your repository here](https://github.com/thomasbnt/awesome-web-monetization)

**Comment by DanCanetti** [comment]
> Could you update [your page](https://danielcanetti.com/demo/monetize-plugin/) ?

[This page](https://danielcanetti.com/demo/monetize-plugin/) is now updated with the latest NPM package. Sorry, I had a few other updates on the site to complete before I deployed. Let me know if you need anything else.

> 🆕 You can [see your repository here](https://github.com/thomasbnt/awesome-web-monetization)

That's awesome! Thanks! 👍

**Comment by thomasbnt** [comment]
> This page is now updated with the latest NPM package. Sorry, I had a few other updates on the site to complete before I deployed. Let me know if you need anything else.

Done ! No blocking content with Ublock. Good! :heavy_check_mark:
